'use client'

import Link from 'next/link'
import { Zap, Clock, FileText, TrendingUp, ArrowRight, AlertTriangle } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'
import { mockDigest } from '@/lib/mock-data'

export default function PublicSharePage() {
  const digest = mockDigest

  const getSignalColor = (score: number) => {
    if (score >= 8) return 'bg-signal-high'
    if (score >= 5) return 'bg-signal-medium'
    return 'bg-signal-low'
  }

  const getSignalTextColor = (score: number) => {
    if (score >= 8) return 'text-signal-high'
    if (score >= 5) return 'text-signal-medium'
    return 'text-signal-low'
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Public header */}
      <header className="border-b border-border bg-card/50">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="text-lg font-semibold">{"What's New?"}</span>
          </div>
          <Link href="/register">
            <Button size="sm">Create your own</Button>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-4xl p-6 lg:p-8">
        {/* Watermark badge */}
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card px-4 py-2 text-sm">
          <Zap className="h-4 w-4 text-primary" />
          <span className="text-muted-foreground">Generated by {"What's New?"}</span>
        </div>

        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold lg:text-4xl">{digest.domain} Intelligence Briefing</h1>
          <div className="mt-4 flex flex-wrap items-center gap-3 text-muted-foreground">
            <span className="flex items-center gap-1">
              <Clock className="h-4 w-4" />
              Last {digest.days} days
            </span>
            <Badge variant="secondary" className="gap-1">
              <FileText className="h-3 w-3" />
              {digest.total_trends} trends
            </Badge>
            <Badge variant="secondary" className="gap-1">
              <TrendingUp className="h-3 w-3" />
              {digest.total_articles} articles analyzed
            </Badge>
          </div>
          <p className="mt-2 text-sm text-muted-foreground">
            Generated {new Date(digest.generated_at).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            })}
          </p>
        </div>

        {/* Trends */}
        <div className="space-y-6">
          {digest.trends
            .sort((a, b) => b.signal_score - a.signal_score)
            .map((trend) => (
              <div 
                key={trend.trend_id}
                className="relative overflow-hidden rounded-xl border border-border bg-card"
              >
                {/* Signal accent bar */}
                <div className={cn("absolute left-0 top-0 bottom-0 w-1", getSignalColor(trend.signal_score))} />
                
                <div className="p-6 pl-8">
                  {/* Header */}
                  <div className="flex items-start justify-between gap-4">
                    <h2 className="text-xl font-semibold leading-tight">{trend.trend_title}</h2>
                    <div className="flex items-center gap-2 shrink-0">
                      <Badge variant="outline" className={cn("font-mono", getSignalTextColor(trend.signal_score))}>
                        Signal {trend.signal_score}/10
                      </Badge>
                    </div>
                  </div>

                  {/* TL;DR */}
                  <p className="mt-3 text-muted-foreground">{trend.tldr}</p>

                  {/* Summary */}
                  <div className="mt-4 text-sm leading-relaxed whitespace-pre-line">
                    {trend.summary}
                  </div>

                  {/* So What */}
                  <div className="mt-4 rounded-lg border-l-4 border-primary bg-primary/5 p-4">
                    <p className="text-sm font-medium text-primary">So What?</p>
                    <p className="mt-1 text-sm">{trend.so_what}</p>
                  </div>

                  {/* Contrast */}
                  {trend.contrast && (
                    <div className="mt-4 rounded-lg border border-warning/30 bg-warning/5 p-4">
                      <div className="flex items-center gap-2 text-warning">
                        <AlertTriangle className="h-4 w-4" />
                        <p className="text-sm font-medium">Sources Disagree</p>
                      </div>
                      <p className="mt-1 text-sm text-muted-foreground">{trend.contrast}</p>
                    </div>
                  )}

                  {/* Sources */}
                  <div className="mt-4 pt-4 border-t border-border">
                    <p className="text-xs text-muted-foreground">
                      Sources: {trend.articles.map(a => a.source).join(' · ')}
                    </p>
                  </div>

                  {/* Entities */}
                  <div className="mt-3 flex flex-wrap gap-2">
                    {trend.key_entities.map((entity) => (
                      <Badge key={entity} variant="secondary" className="text-xs">
                        {entity}
                      </Badge>
                    ))}
                  </div>
                </div>
              </div>
            ))}
        </div>

        {/* CTA Banner */}
        <div className="mt-12 rounded-xl border border-primary/30 bg-gradient-to-br from-primary/10 via-background to-background p-8 text-center">
          <h2 className="text-2xl font-bold">Create your own free digest</h2>
          <p className="mx-auto mt-2 max-w-md text-muted-foreground">
            Get personalized intelligence briefings for your domains. Save hours of reading every week.
          </p>
          <Link href="/register" className="mt-6 inline-block">
            <Button size="lg" className="gap-2">
              Get started free
              <ArrowRight className="h-4 w-4" />
            </Button>
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-8 mt-12">
        <div className="mx-auto max-w-4xl px-6 text-center">
          <div className="flex items-center justify-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="text-lg font-semibold">{"What's New?"}</span>
          </div>
          <p className="mt-2 text-sm text-muted-foreground">
            Domain intelligence for busy professionals
          </p>
        </div>
      </footer>
    </div>
  )
}
